# qux
static-hosts:
    - host: qux.example.com
      root: ../static
    - host: qux.*.example.com
      root: ../static
    - host: qux.*.*.example.com
      root: ../static
    - host: qux.*.*.*.example.com
      root: ../static
