# baz
static-hosts:
    - host: baz.example.com
      root: ../static
    - host: baz.*.example.com
      root: ../static
    - host: baz.*.*.example.com
      root: ../static
    - host: baz.*.*.*.example.com
      root: ../static
