#! /bin/sh

### BEGIN INIT INFO
# Provides:		keter
# Required-Start:	$local_fs $syslog
# Required-Stop:	$local_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Keter: Web app deployment manager
### END INIT INFO

set -e

umask 022

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
KETER=/usr/sbin/keter
CONFIG=/etc/keter.conf
PIDFILE=/var/run/keter.pid
USER=www-data
GROUP=www-data

case "$1" in
  start)
	log_daemon_msg "Starting Keter: Web app deployment mananger" "keter"
	if start-stop-daemon --start --quiet --oknodo --background --user $USER --group $GROUP --make-pidfile --pidfile $PIDFILE --exec $KETER -- $CONFIG; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping Keter: Web app deployment mananger" "keter"
	if start-stop-daemon --stop --quiet --oknodo --user $USER --pidfile $PIDFILE; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  restart)
	log_daemon_msg "Restarting Keter: Web app deployment mananger" "keter"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --user $USER --pidfile $PIDFILE
	if start-stop-daemon --start --quiet --oknodo --background --user $USER --group $GROUP --pidfile $PIDFILE --exec $KETER -- $CONFIG; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  *)
	log_action_msg "Usage: /etc/init.d/keter {start|stop|restart}"
	exit 1
esac

exit 0
